/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveMapRouteImport } from './routes/live-map'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformWorkforceAnnouncementsRouteImport } from './routes/platform.workforce-announcements'
import { Route as PlatformTrainingRouteImport } from './routes/platform.training'
import { Route as PlatformPricingRouteImport } from './routes/platform.pricing'
import { Route as PlatformNotificationsRouteImport } from './routes/platform.notifications'
import { Route as PlatformGamificationRouteImport } from './routes/platform.gamification'
import { Route as PlatformAnnouncementsRouteImport } from './routes/platform.announcements'
import { Route as FleetTrucksRouteImport } from './routes/fleet.trucks'
import { Route as FleetOwnersRouteImport } from './routes/fleet.owners'
import { Route as FleetComplianceRouteImport } from './routes/fleet.compliance'
import { Route as FinanceWithdrawalsRouteImport } from './routes/finance.withdrawals'
import { Route as FinanceWalletsRouteImport } from './routes/finance.wallets'
import { Route as FinanceSubscriptionsRouteImport } from './routes/finance.subscriptions'
import { Route as FinanceRevenueRouteImport } from './routes/finance.revenue'
import { Route as FinanceRefundsRouteImport } from './routes/finance.refunds'
import { Route as FinanceEarningsRouteImport } from './routes/finance.earnings'
import { Route as ComplianceUlipRouteImport } from './routes/compliance.ulip'
import { Route as ComplianceExpiryRouteImport } from './routes/compliance.expiry'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMapRoute = LiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformWorkforceAnnouncementsRoute =
  PlatformWorkforceAnnouncementsRouteImport.update({
    id: '/platform/workforce-announcements',
    path: '/platform/workforce-announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformTrainingRoute = PlatformTrainingRouteImport.update({
  id: '/platform/training',
  path: '/platform/training',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPricingRoute = PlatformPricingRouteImport.update({
  id: '/platform/pricing',
  path: '/platform/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNotificationsRoute = PlatformNotificationsRouteImport.update({
  id: '/platform/notifications',
  path: '/platform/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformGamificationRoute = PlatformGamificationRouteImport.update({
  id: '/platform/gamification',
  path: '/platform/gamification',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAnnouncementsRoute = PlatformAnnouncementsRouteImport.update({
  id: '/platform/announcements',
  path: '/platform/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetTrucksRoute = FleetTrucksRouteImport.update({
  id: '/fleet/trucks',
  path: '/fleet/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetOwnersRoute = FleetOwnersRouteImport.update({
  id: '/fleet/owners',
  path: '/fleet/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetComplianceRoute = FleetComplianceRouteImport.update({
  id: '/fleet/compliance',
  path: '/fleet/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWithdrawalsRoute = FinanceWithdrawalsRouteImport.update({
  id: '/finance/withdrawals',
  path: '/finance/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceWalletsRoute = FinanceWalletsRouteImport.update({
  id: '/finance/wallets',
  path: '/finance/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceSubscriptionsRoute = FinanceSubscriptionsRouteImport.update({
  id: '/finance/subscriptions',
  path: '/finance/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRevenueRoute = FinanceRevenueRouteImport.update({
  id: '/finance/revenue',
  path: '/finance/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRefundsRoute = FinanceRefundsRouteImport.update({
  id: '/finance/refunds',
  path: '/finance/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceEarningsRoute = FinanceEarningsRouteImport.update({
  id: '/finance/earnings',
  path: '/finance/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceUlipRoute = ComplianceUlipRouteImport.update({
  id: '/ulip',
  path: '/ulip',
  getParentRoute: () => ComplianceRoute,
} as any)
const ComplianceExpiryRoute = ComplianceExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => ComplianceRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/compliance': typeof ComplianceRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/workforce': typeof WorkforceRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/compliance/expiry': typeof ComplianceExpiryRoute
  '/compliance/ulip': typeof ComplianceUlipRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/wallets': typeof FinanceWalletsRoute
  '/finance/withdrawals': typeof FinanceWithdrawalsRoute
  '/fleet/compliance': typeof FleetComplianceRoute
  '/fleet/owners': typeof FleetOwnersRoute
  '/fleet/trucks': typeof FleetTrucksRoute
  '/platform/announcements': typeof PlatformAnnouncementsRoute
  '/platform/gamification': typeof PlatformGamificationRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/pricing': typeof PlatformPricingRoute
  '/platform/training': typeof PlatformTrainingRoute
  '/platform/workforce-announcements': typeof PlatformWorkforceAnnouncementsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/compliance': typeof ComplianceRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/workforce': typeof WorkforceRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/compliance/expiry': typeof ComplianceExpiryRoute
  '/compliance/ulip': typeof ComplianceUlipRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/wallets': typeof FinanceWalletsRoute
  '/finance/withdrawals': typeof FinanceWithdrawalsRoute
  '/fleet/compliance': typeof FleetComplianceRoute
  '/fleet/owners': typeof FleetOwnersRoute
  '/fleet/trucks': typeof FleetTrucksRoute
  '/platform/announcements': typeof PlatformAnnouncementsRoute
  '/platform/gamification': typeof PlatformGamificationRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/pricing': typeof PlatformPricingRoute
  '/platform/training': typeof PlatformTrainingRoute
  '/platform/workforce-announcements': typeof PlatformWorkforceAnnouncementsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/compliance': typeof ComplianceRouteWithChildren
  '/customers': typeof CustomersRoute
  '/dispatch': typeof DispatchRoute
  '/drivers': typeof DriversRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/live-map': typeof LiveMapRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/verification': typeof VerificationRoute
  '/workforce': typeof WorkforceRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/compliance/expiry': typeof ComplianceExpiryRoute
  '/compliance/ulip': typeof ComplianceUlipRoute
  '/finance/earnings': typeof FinanceEarningsRoute
  '/finance/refunds': typeof FinanceRefundsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/subscriptions': typeof FinanceSubscriptionsRoute
  '/finance/wallets': typeof FinanceWalletsRoute
  '/finance/withdrawals': typeof FinanceWithdrawalsRoute
  '/fleet/compliance': typeof FleetComplianceRoute
  '/fleet/owners': typeof FleetOwnersRoute
  '/fleet/trucks': typeof FleetTrucksRoute
  '/platform/announcements': typeof PlatformAnnouncementsRoute
  '/platform/gamification': typeof PlatformGamificationRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/pricing': typeof PlatformPricingRoute
  '/platform/training': typeof PlatformTrainingRoute
  '/platform/workforce-announcements': typeof PlatformWorkforceAnnouncementsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/compliance'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/reports'
    | '/reset-password'
    | '/support'
    | '/verification'
    | '/workforce'
    | '/bookings/$id'
    | '/compliance/expiry'
    | '/compliance/ulip'
    | '/finance/earnings'
    | '/finance/refunds'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/finance/wallets'
    | '/finance/withdrawals'
    | '/fleet/compliance'
    | '/fleet/owners'
    | '/fleet/trucks'
    | '/platform/announcements'
    | '/platform/gamification'
    | '/platform/notifications'
    | '/platform/pricing'
    | '/platform/training'
    | '/platform/workforce-announcements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/compliance'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/reports'
    | '/reset-password'
    | '/support'
    | '/verification'
    | '/workforce'
    | '/bookings/$id'
    | '/compliance/expiry'
    | '/compliance/ulip'
    | '/finance/earnings'
    | '/finance/refunds'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/finance/wallets'
    | '/finance/withdrawals'
    | '/fleet/compliance'
    | '/fleet/owners'
    | '/fleet/trucks'
    | '/platform/announcements'
    | '/platform/gamification'
    | '/platform/notifications'
    | '/platform/pricing'
    | '/platform/training'
    | '/platform/workforce-announcements'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/compliance'
    | '/customers'
    | '/dispatch'
    | '/drivers'
    | '/forgot-password'
    | '/live-map'
    | '/login'
    | '/reports'
    | '/reset-password'
    | '/support'
    | '/verification'
    | '/workforce'
    | '/bookings/$id'
    | '/compliance/expiry'
    | '/compliance/ulip'
    | '/finance/earnings'
    | '/finance/refunds'
    | '/finance/revenue'
    | '/finance/subscriptions'
    | '/finance/wallets'
    | '/finance/withdrawals'
    | '/fleet/compliance'
    | '/fleet/owners'
    | '/fleet/trucks'
    | '/platform/announcements'
    | '/platform/gamification'
    | '/platform/notifications'
    | '/platform/pricing'
    | '/platform/training'
    | '/platform/workforce-announcements'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  ComplianceRoute: typeof ComplianceRouteWithChildren
  CustomersRoute: typeof CustomersRoute
  DispatchRoute: typeof DispatchRoute
  DriversRoute: typeof DriversRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LiveMapRoute: typeof LiveMapRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  VerificationRoute: typeof VerificationRoute
  WorkforceRoute: typeof WorkforceRoute
  FinanceEarningsRoute: typeof FinanceEarningsRoute
  FinanceRefundsRoute: typeof FinanceRefundsRoute
  FinanceRevenueRoute: typeof FinanceRevenueRoute
  FinanceSubscriptionsRoute: typeof FinanceSubscriptionsRoute
  FinanceWalletsRoute: typeof FinanceWalletsRoute
  FinanceWithdrawalsRoute: typeof FinanceWithdrawalsRoute
  FleetComplianceRoute: typeof FleetComplianceRoute
  FleetOwnersRoute: typeof FleetOwnersRoute
  FleetTrucksRoute: typeof FleetTrucksRoute
  PlatformAnnouncementsRoute: typeof PlatformAnnouncementsRoute
  PlatformGamificationRoute: typeof PlatformGamificationRoute
  PlatformNotificationsRoute: typeof PlatformNotificationsRoute
  PlatformPricingRoute: typeof PlatformPricingRoute
  PlatformTrainingRoute: typeof PlatformTrainingRoute
  PlatformWorkforceAnnouncementsRoute: typeof PlatformWorkforceAnnouncementsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-map': {
      id: '/live-map'
      path: '/live-map'
      fullPath: '/live-map'
      preLoaderRoute: typeof LiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/workforce-announcements': {
      id: '/platform/workforce-announcements'
      path: '/platform/workforce-announcements'
      fullPath: '/platform/workforce-announcements'
      preLoaderRoute: typeof PlatformWorkforceAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/training': {
      id: '/platform/training'
      path: '/platform/training'
      fullPath: '/platform/training'
      preLoaderRoute: typeof PlatformTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/pricing': {
      id: '/platform/pricing'
      path: '/platform/pricing'
      fullPath: '/platform/pricing'
      preLoaderRoute: typeof PlatformPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/notifications': {
      id: '/platform/notifications'
      path: '/platform/notifications'
      fullPath: '/platform/notifications'
      preLoaderRoute: typeof PlatformNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/gamification': {
      id: '/platform/gamification'
      path: '/platform/gamification'
      fullPath: '/platform/gamification'
      preLoaderRoute: typeof PlatformGamificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/announcements': {
      id: '/platform/announcements'
      path: '/platform/announcements'
      fullPath: '/platform/announcements'
      preLoaderRoute: typeof PlatformAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/trucks': {
      id: '/fleet/trucks'
      path: '/fleet/trucks'
      fullPath: '/fleet/trucks'
      preLoaderRoute: typeof FleetTrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/owners': {
      id: '/fleet/owners'
      path: '/fleet/owners'
      fullPath: '/fleet/owners'
      preLoaderRoute: typeof FleetOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/compliance': {
      id: '/fleet/compliance'
      path: '/fleet/compliance'
      fullPath: '/fleet/compliance'
      preLoaderRoute: typeof FleetComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/withdrawals': {
      id: '/finance/withdrawals'
      path: '/finance/withdrawals'
      fullPath: '/finance/withdrawals'
      preLoaderRoute: typeof FinanceWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/wallets': {
      id: '/finance/wallets'
      path: '/finance/wallets'
      fullPath: '/finance/wallets'
      preLoaderRoute: typeof FinanceWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/subscriptions': {
      id: '/finance/subscriptions'
      path: '/finance/subscriptions'
      fullPath: '/finance/subscriptions'
      preLoaderRoute: typeof FinanceSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/revenue': {
      id: '/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof FinanceRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/refunds': {
      id: '/finance/refunds'
      path: '/finance/refunds'
      fullPath: '/finance/refunds'
      preLoaderRoute: typeof FinanceRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/earnings': {
      id: '/finance/earnings'
      path: '/finance/earnings'
      fullPath: '/finance/earnings'
      preLoaderRoute: typeof FinanceEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/ulip': {
      id: '/compliance/ulip'
      path: '/ulip'
      fullPath: '/compliance/ulip'
      preLoaderRoute: typeof ComplianceUlipRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/compliance/expiry': {
      id: '/compliance/expiry'
      path: '/expiry'
      fullPath: '/compliance/expiry'
      preLoaderRoute: typeof ComplianceExpiryRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
  }
}

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface ComplianceRouteChildren {
  ComplianceExpiryRoute: typeof ComplianceExpiryRoute
  ComplianceUlipRoute: typeof ComplianceUlipRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  ComplianceExpiryRoute: ComplianceExpiryRoute,
  ComplianceUlipRoute: ComplianceUlipRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRouteWithChildren,
  ComplianceRoute: ComplianceRouteWithChildren,
  CustomersRoute: CustomersRoute,
  DispatchRoute: DispatchRoute,
  DriversRoute: DriversRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LiveMapRoute: LiveMapRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  VerificationRoute: VerificationRoute,
  WorkforceRoute: WorkforceRoute,
  FinanceEarningsRoute: FinanceEarningsRoute,
  FinanceRefundsRoute: FinanceRefundsRoute,
  FinanceRevenueRoute: FinanceRevenueRoute,
  FinanceSubscriptionsRoute: FinanceSubscriptionsRoute,
  FinanceWalletsRoute: FinanceWalletsRoute,
  FinanceWithdrawalsRoute: FinanceWithdrawalsRoute,
  FleetComplianceRoute: FleetComplianceRoute,
  FleetOwnersRoute: FleetOwnersRoute,
  FleetTrucksRoute: FleetTrucksRoute,
  PlatformAnnouncementsRoute: PlatformAnnouncementsRoute,
  PlatformGamificationRoute: PlatformGamificationRoute,
  PlatformNotificationsRoute: PlatformNotificationsRoute,
  PlatformPricingRoute: PlatformPricingRoute,
  PlatformTrainingRoute: PlatformTrainingRoute,
  PlatformWorkforceAnnouncementsRoute: PlatformWorkforceAnnouncementsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
